<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ARBUEL018" name="Test" tests="5" failures="3" timestamp="11 Dec 2015 20:29:36 GMT" time="68.892" errors="0">
  <testcase name="testLoginUserInvalidoAdm2" time="6.0" classname="testcases.Login">
    <failure type="java.lang.AssertionError" message="expected [Login] but found [yii\base\ErrorException]">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [yii\base\ErrorException]
	at testcases.Login.testLoginUserInvalidoAdm2(Login.java:48)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testLoginUserInvalidoAdm2 -->
  <testcase name="testLoginUserInvalidoAdmin2" time="6.092" classname="testcases.Login">
    <failure type="java.lang.AssertionError" message="expected [Login] but found [yii\base\ErrorException]">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [yii\base\ErrorException]
	at testcases.Login.testLoginUserInvalidoAdmin2(Login.java:37)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testLoginUserInvalidoAdmin2 -->
  <testcase name="testLoginUserInvalidoCaracteresRaros" time="6.09" classname="testcases.Login">
    <failure type="java.lang.AssertionError" message="expected [Login] but found [yii\base\ErrorException]">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [yii\base\ErrorException]
	at testcases.Login.testLoginUserInvalidoCaracteresRaros(Login.java:71)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testLoginUserInvalidoCaracteresRaros -->
  <testcase name="testLoginUserInvalidoEspacioVacio" time="5.338" classname="testcases.Login"/>
  <testcase name="testLoginUserValidoAdmin" time="6.089" classname="testcases.Login"/>
</testsuite> <!-- Test -->
